version: "3.3"

services:
    redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis:/data
    networks:
      - internal
    command: redis-server --appendonly yes --requirepass thisismirzaandthisisredis_redisisakvstoragedatabaseandmirzaisgoingtouseitascacheserver

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    restart: always
    volumes:
      - ./docker/mqtt:/mosquitto/config
    ports:
      - 1883:1883
    command: mosquitto -c /mosquitto/config/mosquitto.conf -v
    networks:
      - internal


networks:
  internal:
